### ISSUE TITLE
turn on indications for the Spot-Check measurement characteristic 

### ISSUE THREAD

**Issue by merylb** [andybb/nonin-3230-ble#2]
Hello, 
I'm trying to enable indications  for the spot check measurement characteristic so as getting access to the temporarily stored PLX Spot-Check measurements? have you any idea about this?

thanks in advance.

**Comment by andreasdri** [comment]
Hi! 
This library was written to work only with the proprietary Nonin Oxymetry Service and not the standard Bluetooth SIG Pulse Oximeter Service. My version/software revision of Nonin 3230 was not new enough to support the new standard service. 

I see from the integration guide that it is possible to achieve what you want by doing the following:

> The collector can turn on indications for the Spot-Check measurement characteristic by writing “02 00” to its CCCD (Client Characteristic Configuration Descriptor).

I can send you this integration guide if you don't have access to it.

**Comment by merylb** [comment]
thank you so much, I try sending “02 00”  and it work fine.

**Comment by andreasdri** [comment]
Nice to hear! 😄
